# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Gallery_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Gallery_App
  pod 'SDWebImage', '~> 5.0'
  target 'MVVM_Gallery_AppUITests' do
    # Pods for testing
  end

end
